name: CD

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  call-external:
    uses: jina-ai/workflows-executors/.github/workflows/cd.yml@master
    with:
      event_name: ${{ github.event_name }}
    secrets:
      jinahub_token: ${{ secrets.JINAHUB_TOKEN }}
