name: CI

on: [pull_request]

jobs:
  hub-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: tests
        run: |
          sudo apt-get install libsndfile-dev
          ./scripts/tests.sh